class Session < Sequel::Model
  many_to_one :user
end

# Table: sessions
# Columns:
#  id         | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  user_id    | integer                     | NOT NULL
#  token      | text                        | NOT NULL DEFAULT gen_random_uuid()
#  user_agent | text                        |
#  ip_address | inet                        |
#  created_at | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
#  updated_at | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
# Indexes:
#  sessions_pkey          | PRIMARY KEY btree (id)
#  sessions_token_index   | UNIQUE btree (token)
#  sessions_user_id_index | btree (user_id)
# Foreign key constraints:
#  sessions_user_id_fkey | (user_id) REFERENCES users(id)
