# frozen_string_literal: true

require 'bcrypt'

class User < Sequel::Model
  include BCrypt

  one_to_many :sessions

  def self.authenticate_by(email:, password:)
    user = first(email: email&.downcase)
    return nil unless user&.authenticate?(password)

    user
  end

  def password=(new_password)
    self.password_digest = Password.create(new_password)
  end

  def authenticate?(attempted_password)
    return false unless password_digest

    password = Password.new(password_digest)
    password == attempted_password
  end
end

# Table: users
# Columns:
#  id                     | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  email                  | text                        | NOT NULL
#  username               | text                        | NOT NULL
#  password_digest        | text                        | NOT NULL
#  timezone               | text                        |
#  options                | jsonb                       | DEFAULT '{}'::jsonb
#  settings               | jsonb                       | DEFAULT '{}'::jsonb
#  status                 | text                        | DEFAULT 'active'::text
#  created_at             | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
#  updated_at             | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
#  info                   | text                        |
#  reset_password_token   | text                        |
#  reset_password_sent_at | timestamp without time zone |
#  confirmation_token     | text                        |
#  confirmed_at           | timestamp without time zone |
#  confirmation_sent_at   | timestamp without time zone |
#  unconfirmed_email      | text                        |
#  failed_attempts        | integer                     | NOT NULL DEFAULT 0
#  unlock_token           | text                        | NOT NULL DEFAULT gen_random_uuid()
#  locked_at              | timestamp without time zone | DEFAULT CURRENT_TIMESTAMP
# Indexes:
#  users_pkey                       | PRIMARY KEY btree (id)
#  users_confirmation_token_index   | UNIQUE btree (confirmation_token)
#  users_email_index                | UNIQUE btree (email)
#  users_reset_password_token_index | UNIQUE btree (reset_password_token)
#  users_unconfirmed_email_index    | UNIQUE btree (unconfirmed_email)
#  users_unlock_token_index         | UNIQUE btree (unlock_token)
#  users_username_index             | UNIQUE btree (username)
#  users_status_index               | btree (status)
# Referenced By:
#  sessions | sessions_user_id_fkey | (user_id) REFERENCES users(id)
